/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gymmanagementproject;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Tanis
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LOginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        UserNamePanel = new javax.swing.JPanel();
        UserName = new javax.swing.JLabel();
        UserIdPanel = new javax.swing.JPanel();
        UserId = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel2.setText("USERNAME");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("  WELCOME     TO        SITA    GYM        MANAGEMENT ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 710, -1));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserNamePanel.setBackground(new java.awt.Color(153, 153, 153));
        UserNamePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UserNamePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UserNamePanelMouseExited(evt);
            }
        });

        UserName.setText("USERNAME");

        javax.swing.GroupLayout UserNamePanelLayout = new javax.swing.GroupLayout(UserNamePanel);
        UserNamePanel.setLayout(UserNamePanelLayout);
        UserNamePanelLayout.setHorizontalGroup(
            UserNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserNamePanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(UserName)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        UserNamePanelLayout.setVerticalGroup(
            UserNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserNamePanelLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(UserName)
                .addGap(26, 26, 26))
        );

        jPanel3.add(UserNamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        UserIdPanel.setBackground(new java.awt.Color(153, 153, 153));
        UserIdPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UserIdPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UserIdPanelMouseExited(evt);
            }
        });

        UserId.setText("USER_ID");

        javax.swing.GroupLayout UserIdPanelLayout = new javax.swing.GroupLayout(UserIdPanel);
        UserIdPanel.setLayout(UserIdPanelLayout);
        UserIdPanelLayout.setHorizontalGroup(
            UserIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserIdPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UserId, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        UserIdPanelLayout.setVerticalGroup(
            UserIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserIdPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(UserId)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel3.add(UserIdPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 220, 90));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 220, 400));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 132, 170, 40));
        jPanel1.add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 170, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 333, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserNamePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserNamePanelMouseEntered
        // TODO add your handling code here:
         Color color = new Color(01,0,0);
        UserNamePanel.setBackground(color);
        UserName.setForeground(Color.white);
        
    }//GEN-LAST:event_UserNamePanelMouseEntered

    private void UserIdPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserIdPanelMouseEntered
        // TODO add your handling code here:
         Color color = new Color(01,0,0);
        UserIdPanel.setBackground(color);
        UserId.setForeground(Color.white);
        
    }//GEN-LAST:event_UserIdPanelMouseEntered

    private void UserNamePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserNamePanelMouseExited
        // TODO add your handling code here:
          Color color = new Color(153,153,153);
        UserNamePanel.setBackground(color);
        UserName.setForeground(Color.black);
    }//GEN-LAST:event_UserNamePanelMouseExited

    private void UserIdPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserIdPanelMouseExited
        // TODO add your handling code here:
         Color color = new Color(153,153,153);
        UserIdPanel.setBackground(color);
        UserId.setForeground(Color.black);
    }//GEN-LAST:event_UserIdPanelMouseExited

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
         if( Name.getText().isEmpty()&& Id.getText().isEmpty()){
JOptionPane.showMessageDialog(this,"enter all details");
}else{
if(Name.getText().isEmpty()){
    JOptionPane.showMessageDialog(this,"enter the NAME ")  ;
    
    
}else if (Id.getText().isEmpty() ){
   JOptionPane.showMessageDialog(this,"enter the USER_ID");
    
}
// password ke leye variable set krne kaga hu

    
else{
    if(Name.getText().equals("tanish")&& Id.getText().equals("7807935750")){
        JOptionPane.showMessageDialog(this,"welcome to the gym ");
        System.out.println("welcome! to GYM MANAGEMENT ");

    }
    else{
        JOptionPane.showMessageDialog(this,"incorrect details");
        System.out.println("INCORRCET DETAILS  PLZ CHECK IT ");
    }
}
}
        
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if( Name.getText().isEmpty()&& Id.getText().isEmpty()){
JOptionPane.showMessageDialog(this,"enter all details");
}else{
if(Name.getText().isEmpty()){
    JOptionPane.showMessageDialog(this,"enter the NAME ")  ;
    
    
}else if (Id.getText().isEmpty() ){
   JOptionPane.showMessageDialog(this,"enter the USER_ID");
    
}
// password ke leye variable set krne kaga hu

    
else{
    if(Name.getText().equals("tanish")&& Id.getText().equals("7807935750")){
        JOptionPane.showMessageDialog(this,"welcome to the gym ");
        System.out.println("welcome! to GYM MANAGEMENT ");
         MembershipRegistrationPage object = new MembershipRegistrationPage();
    object.setVisible(true);
    dispose();

    }
    else{
        JOptionPane.showMessageDialog(this,"incorrect details");
        System.out.println("INCORRCET DETAILS  PLZ CHECK IT ");
    }
   
    
}
}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel UserId;
    private javax.swing.JPanel UserIdPanel;
    private javax.swing.JLabel UserName;
    private javax.swing.JPanel UserNamePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    
}
